name: SecRandom_lutter
description: "基于 Material Design 3 的随机点名应用。"
publish_to: 'none'
version: 0.0.2+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  animations: ^2.0.11
  uuid: ^4.3.3
  path_provider: ^2.1.2
  path: ^1.9.0
  universal_html: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
